<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Contact;
use App\Models\ContactActivity;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class Top30CompaniesSeeder extends Seeder
{
    public function run()
    {
        // 1. Wipe existing contacts and activities safely
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        ContactActivity::truncate();
        Contact::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $admin = User::first();
        $adminId = $admin ? $admin->id : 1;
        $users = User::pluck('id')->toArray();
        if (empty($users)) {
            $users = [$adminId];
        }

        $stages = ['new', 'contacted', 'qualified', 'proposal', 'negotiation'];
        $sources = ['website', 'google_ads', 'meta_ads', 'linkedin', 'instagram', 'whatsapp', 'email', 'referral', 'manual'];

        $companies = [
            [
                'company' => 'Apple Inc',
                'website' => 'https://apple.com',
                'phone' => '+1 408 996 1010',
                'email' => 'contact@apple.com',
                'first_name' => 'Tim',
                'last_name' => 'Cook',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 250000,
                'lead_score' => 95,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'website',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Enterprise Mobility Strategy Call',
                    'description' => 'Discussed custom iOS application deployment for internal workforce management.',
                ],
            ],
            [
                'company' => 'Microsoft Corporation',
                'website' => 'https://microsoft.com',
                'phone' => '+1 425 882 8080',
                'email' => 'enterprise@microsoft.com',
                'first_name' => 'Satya',
                'last_name' => 'Nadella',
                'job_title' => 'Executive Chairman & CEO',
                'estimated_value' => 320000,
                'lead_score' => 98,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Azure Cloud & AI Integration',
                    'description' => 'Aligned on contract terms for custom Azure OpenAI middleware development.',
                ],
            ],
            [
                'company' => 'Google / Alphabet',
                'website' => 'https://google.com',
                'phone' => '+1 650 253 0000',
                'email' => 'partner@google.com',
                'first_name' => 'Sundar',
                'last_name' => 'Pichai',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 290000,
                'lead_score' => 92,
                'priority' => 'high',
                'stage' => 'qualified',
                'source' => 'google_ads',
                'activity' => [
                    'type' => 'email',
                    'title' => 'API Integration Specifications Sent',
                    'description' => 'Shared architecture documentation for Google Workspace CRM sync.',
                ],
            ],
            [
                'company' => 'Amazon',
                'website' => 'https://amazon.com',
                'phone' => '+1 206 266 1000',
                'email' => 'corporate@amazon.com',
                'first_name' => 'Andy',
                'last_name' => 'Jassy',
                'job_title' => 'President & CEO',
                'estimated_value' => 450000,
                'lead_score' => 88,
                'priority' => 'high',
                'stage' => 'contacted',
                'source' => 'referral',
                'activity' => [
                    'type' => 'call',
                    'title' => 'AWS Marketplace Partnership',
                    'description' => 'Explored listing AppLead CRM on AWS Marketplace for global enterprise clients.',
                ],
            ],
            [
                'company' => 'Meta Platforms',
                'website' => 'https://meta.com',
                'phone' => '+1 650 543 4800',
                'email' => 'growth@meta.com',
                'first_name' => 'Mark',
                'last_name' => 'Zuckerberg',
                'job_title' => 'Founder & CEO',
                'estimated_value' => 180000,
                'lead_score' => 85,
                'priority' => 'medium',
                'stage' => 'new',
                'source' => 'meta_ads',
                'activity' => [
                    'type' => 'note',
                    'title' => 'Inbound Campaign Inquiry',
                    'description' => 'Received lead via Meta Ads campaign for custom WhatsApp CRM automation.',
                ],
            ],
            [
                'company' => 'Tesla',
                'website' => 'https://tesla.com',
                'phone' => '+1 800 613 8840',
                'email' => 'fleet@tesla.com',
                'first_name' => 'Elon',
                'last_name' => 'Musk',
                'job_title' => 'Technoking & CEO',
                'estimated_value' => 380000,
                'lead_score' => 96,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'website',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Fleet Sales Management Portal',
                    'description' => 'Demonstrated real-time lead tracking dashboard for commercial vehicle orders.',
                ],
            ],
            [
                'company' => 'NVIDIA Corporation',
                'website' => 'https://nvidia.com',
                'phone' => '+1 408 486 2000',
                'email' => 'ai-enterprise@nvidia.com',
                'first_name' => 'Jensen',
                'last_name' => 'Huang',
                'job_title' => 'President & CEO',
                'estimated_value' => 500000,
                'lead_score' => 99,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'call',
                    'title' => 'GPU Infrastructure CRM Sync',
                    'description' => 'Reviewed master service agreement for enterprise GPU telemetry analytics.',
                ],
            ],
            [
                'company' => 'Netflix',
                'website' => 'https://netflix.com',
                'phone' => '+1 408 540 3700',
                'email' => 'partners@netflix.com',
                'first_name' => 'Ted',
                'last_name' => 'Sarandos',
                'job_title' => 'Co-CEO',
                'estimated_value' => 210000,
                'lead_score' => 84,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'email',
                'activity' => [
                    'type' => 'email',
                    'title' => 'Content Licensing Lead Portal',
                    'description' => 'Sent initial pitch for automated distribution & rights tracking portal.',
                ],
            ],
            [
                'company' => 'Adobe',
                'website' => 'https://adobe.com',
                'phone' => '+1 408 536 6000',
                'email' => 'enterprise@adobe.com',
                'first_name' => 'Shantanu',
                'last_name' => 'Narayen',
                'job_title' => 'Chairman & CEO',
                'estimated_value' => 195000,
                'lead_score' => 89,
                'priority' => 'high',
                'stage' => 'qualified',
                'source' => 'website',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Creative Cloud API Workshop',
                    'description' => 'Held technical discovery on integrating Document Cloud signature APIs.',
                ],
            ],
            [
                'company' => 'Salesforce',
                'website' => 'https://salesforce.com',
                'phone' => '+1 800 667 6389',
                'email' => 'info@salesforce.com',
                'first_name' => 'Marc',
                'last_name' => 'Benioff',
                'job_title' => 'Chair & CEO',
                'estimated_value' => 280000,
                'lead_score' => 91,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'referral',
                'activity' => [
                    'type' => 'call',
                    'title' => 'AppExchange Ecosystem Discussion',
                    'description' => 'Reviewed custom connector architecture for bi-directional data sync.',
                ],
            ],
            [
                'company' => 'Spotify',
                'website' => 'https://spotify.com',
                'phone' => '+46 8 502 555 50',
                'email' => 'brands@spotify.com',
                'first_name' => 'Daniel',
                'last_name' => 'Ek',
                'job_title' => 'Founder & CEO',
                'estimated_value' => 160000,
                'lead_score' => 82,
                'priority' => 'medium',
                'stage' => 'new',
                'source' => 'instagram',
                'activity' => [
                    'type' => 'note',
                    'title' => 'Audio Ad Sales Inquiry',
                    'description' => 'Inbound lead interested in custom advertiser CRM portal.',
                ],
            ],
            [
                'company' => 'Uber Technologies',
                'website' => 'https://uber.com',
                'phone' => '+1 833 872 8237',
                'email' => 'business@uber.com',
                'first_name' => 'Dara',
                'last_name' => 'Khosrowshahi',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 310000,
                'lead_score' => 93,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Uber for Business Corporate Rates',
                    'description' => 'Finalized terms for national driver onboarding management system.',
                ],
            ],
            [
                'company' => 'Airbnb',
                'website' => 'https://airbnb.com',
                'phone' => '+1 415 800 5959',
                'email' => 'host-partners@airbnb.com',
                'first_name' => 'Brian',
                'last_name' => 'Chesky',
                'job_title' => 'Co-Founder & CEO',
                'estimated_value' => 230000,
                'lead_score' => 87,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'website',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Superhost Enterprise Support',
                    'description' => 'Discussed automated guest communication & CRM workflow triggers.',
                ],
            ],
            [
                'company' => 'Stripe',
                'website' => 'https://stripe.com',
                'phone' => '+1 888 963 8969',
                'email' => 'sales@stripe.com',
                'first_name' => 'Patrick',
                'last_name' => 'Collison',
                'job_title' => 'Co-Founder & CEO',
                'estimated_value' => 410000,
                'lead_score' => 97,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'manual',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Stripe Connect Billing Integration',
                    'description' => 'Reviewed recurring subscription billing gateway setup for enterprise SaaS.',
                ],
            ],
            [
                'company' => 'Slack Technologies',
                'website' => 'https://slack.com',
                'phone' => '+1 800 500 7522',
                'email' => 'enterprise@slack.com',
                'first_name' => 'Stewart',
                'last_name' => 'Butterfield',
                'job_title' => 'Co-Founder',
                'estimated_value' => 175000,
                'lead_score' => 80,
                'priority' => 'medium',
                'stage' => 'qualified',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'email',
                    'title' => 'Slack Bot Webhook Demo',
                    'description' => 'Sent interactive video demo of instant Slack notifications for hot leads.',
                ],
            ],
            [
                'company' => 'Zoom Video Communications',
                'website' => 'https://zoom.us',
                'phone' => '+1 888 799 9666',
                'email' => 'sales@zoom.us',
                'first_name' => 'Eric',
                'last_name' => 'Yuan',
                'job_title' => 'Founder & CEO',
                'estimated_value' => 205000,
                'lead_score' => 86,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'google_ads',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Zoom Meetings API Integration',
                    'description' => 'Conducted discovery call on auto-generating Zoom meeting links upon scheduling.',
                ],
            ],
            [
                'company' => 'Atlassian',
                'website' => 'https://atlassian.com',
                'phone' => '+1 415 701 1110',
                'email' => 'info@atlassian.com',
                'first_name' => 'Mike',
                'last_name' => 'Cannon-Brookes',
                'job_title' => 'Co-CEO',
                'estimated_value' => 260000,
                'lead_score' => 90,
                'priority' => 'high',
                'stage' => 'qualified',
                'source' => 'website',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Jira & Confluence Workflow Sync',
                    'description' => 'Met with engineering lead to map Jira ticket creation from closed-won leads.',
                ],
            ],
            [
                'company' => 'Shopify',
                'website' => 'https://shopify.com',
                'phone' => '+1 888 746 7439',
                'email' => 'plus@shopify.com',
                'first_name' => 'Tobi',
                'last_name' => 'Lütke',
                'job_title' => 'Founder & CEO',
                'estimated_value' => 340000,
                'lead_score' => 94,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'referral',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Shopify Plus Merchant CRM Portal',
                    'description' => 'Discussed custom B2B merchant portal for high-volume store owners.',
                ],
            ],
            [
                'company' => 'IBM Corporation',
                'website' => 'https://ibm.com',
                'phone' => '+1 800 426 4968',
                'email' => 'watson@ibm.com',
                'first_name' => 'Arvind',
                'last_name' => 'Krishna',
                'job_title' => 'Chairman & CEO',
                'estimated_value' => 295000,
                'lead_score' => 91,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'email',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Watson AI Analytics Contract',
                    'description' => 'Reviewed legal compliance & data sovereignty clauses for enterprise deployment.',
                ],
            ],
            [
                'company' => 'Oracle Corporation',
                'website' => 'https://oracle.com',
                'phone' => '+1 800 633 0738',
                'email' => 'cloud@oracle.com',
                'first_name' => 'Safra',
                'last_name' => 'Catz',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 370000,
                'lead_score' => 93,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Oracle Autonomous DB Connector',
                    'description' => 'Discussed high-throughput SQL database syncing for real-time reporting.',
                ],
            ],
            [
                'company' => 'Intel Corporation',
                'website' => 'https://intel.com',
                'phone' => '+1 408 765 8080',
                'email' => 'foundry@intel.com',
                'first_name' => 'Pat',
                'last_name' => 'Gelsinger',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 225000,
                'lead_score' => 83,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'website',
                'activity' => [
                    'type' => 'email',
                    'title' => 'Hardware Supply Chain CRM Inquiry',
                    'description' => 'Sent custom pitch deck detailing multi-site inventory tracking.',
                ],
            ],
            [
                'company' => 'Cisco Systems',
                'website' => 'https://cisco.com',
                'phone' => '+1 408 526 4000',
                'email' => 'solutions@cisco.com',
                'first_name' => 'Chuck',
                'last_name' => 'Robbins',
                'job_title' => 'Chair & CEO',
                'estimated_value' => 275000,
                'lead_score' => 88,
                'priority' => 'high',
                'stage' => 'qualified',
                'source' => 'manual',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Network Infrastructure Lead Router',
                    'description' => 'Confirmed requirements for automated regional lead assignment routing.',
                ],
            ],
            [
                'company' => 'Samsung Electronics',
                'website' => 'https://samsung.com',
                'phone' => '+82 2 2255 0114',
                'email' => 'b2b@samsung.com',
                'first_name' => 'JH',
                'last_name' => 'Han',
                'job_title' => 'Vice Chairman & CEO',
                'estimated_value' => 390000,
                'lead_score' => 95,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'referral',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Global Knox Security Integration',
                    'description' => 'Finalized security audit protocol for mobile CRM deployment across Asia-Pacific.',
                ],
            ],
            [
                'company' => 'Sony Group',
                'website' => 'https://sony.com',
                'phone' => '+81 3 6748 2111',
                'email' => 'corporate@sony.com',
                'first_name' => 'Kenichiro',
                'last_name' => 'Yoshida',
                'job_title' => 'Chairman & CEO',
                'estimated_value' => 190000,
                'lead_score' => 81,
                'priority' => 'medium',
                'stage' => 'new',
                'source' => 'website',
                'activity' => [
                    'type' => 'note',
                    'title' => 'PlayStation Developer Partner Inquiry',
                    'description' => 'New lead submitted form for partner developer onboarding CRM.',
                ],
            ],
            [
                'company' => 'Nike',
                'website' => 'https://nike.com',
                'phone' => '+1 503 671 6453',
                'email' => 'direct@nike.com',
                'first_name' => 'John',
                'last_name' => 'Donahoe',
                'job_title' => 'President & CEO',
                'estimated_value' => 240000,
                'lead_score' => 86,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'instagram',
                'activity' => [
                    'type' => 'call',
                    'title' => 'Direct-to-Consumer VIP Sales',
                    'description' => 'Discussed high-value athlete & influencer relationship management features.',
                ],
            ],
            [
                'company' => 'BMW Group',
                'website' => 'https://bmw.com',
                'phone' => '+49 89 382 0',
                'email' => 'corporate@bmw.com',
                'first_name' => 'Oliver',
                'last_name' => 'Zipse',
                'job_title' => 'Chairman of Board',
                'estimated_value' => 310000,
                'lead_score' => 90,
                'priority' => 'high',
                'stage' => 'qualified',
                'source' => 'linkedin',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'ConnectedDrive Fleet CRM',
                    'description' => 'Demonstrated telematics-driven maintenance reminder automation.',
                ],
            ],
            [
                'company' => 'The Walt Disney Company',
                'website' => 'https://disney.com',
                'phone' => '+1 818 560 1000',
                'email' => 'parks@disney.com',
                'first_name' => 'Bob',
                'last_name' => 'Iger',
                'job_title' => 'Chief Executive Officer',
                'estimated_value' => 330000,
                'lead_score' => 92,
                'priority' => 'high',
                'stage' => 'proposal',
                'source' => 'referral',
                'activity' => [
                    'type' => 'email',
                    'title' => 'Parks & Experiences Booking Portal',
                    'description' => 'Submitted custom proposal for enterprise hospitality lead distribution.',
                ],
            ],
            [
                'company' => 'Walmart',
                'website' => 'https://walmart.com',
                'phone' => '+1 800 925 6278',
                'email' => 'suppliers@walmart.com',
                'first_name' => 'Doug',
                'last_name' => 'McMillon',
                'job_title' => 'President & CEO',
                'estimated_value' => 480000,
                'lead_score' => 97,
                'priority' => 'high',
                'stage' => 'negotiation',
                'source' => 'manual',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'Supplier Portal & Vendor CRM',
                    'description' => 'Conducted final pricing negotiation for 5,000 retail supplier licenses.',
                ],
            ],
            [
                'company' => 'PayPal',
                'website' => 'https://paypal.com',
                'phone' => '+1 888 221 1161',
                'email' => 'merchant@paypal.com',
                'first_name' => 'Alex',
                'last_name' => 'Chriss',
                'job_title' => 'President & CEO',
                'estimated_value' => 200000,
                'lead_score' => 85,
                'priority' => 'medium',
                'stage' => 'contacted',
                'source' => 'website',
                'activity' => [
                    'type' => 'call',
                    'title' => 'B2B Merchant Lead Routing',
                    'description' => 'Reviewed high-risk merchant onboarding workflow integration.',
                ],
            ],
            [
                'company' => 'Square / Block',
                'website' => 'https://square.com',
                'phone' => '+1 855 700 6000',
                'email' => 'sellers@square.com',
                'first_name' => 'Jack',
                'last_name' => 'Dorsey',
                'job_title' => 'Block Head & CEO',
                'estimated_value' => 215000,
                'lead_score' => 87,
                'priority' => 'medium',
                'stage' => 'qualified',
                'source' => 'google_ads',
                'activity' => [
                    'type' => 'meeting',
                    'title' => 'POS Terminal CRM Integration',
                    'description' => 'Met with hardware product team to build automated customer feedback sync.',
                ],
            ],
        ];

        foreach ($companies as $idx => $comp) {
            $assignedUserId = $users[$idx % count($users)];

            $customFields = [
                'website' => $comp['website'],
                'designation' => $comp['job_title'],
                'service_requested' => 'Enterprise Web & CRM System',
                'estimated_value' => (float) $comp['estimated_value'],
                'lead_score' => (int) $comp['lead_score'],
                'priority' => $comp['priority'],
                'stage' => $comp['stage'],
                'notes' => 'Top-tier enterprise client record.',
            ];

            $contact = Contact::create([
                'first_name' => $comp['first_name'],
                'last_name' => $comp['last_name'],
                'email' => $comp['email'],
                'phone' => $comp['phone'],
                'company' => $comp['company'],
                'job_title' => $comp['job_title'],
                'source' => $comp['source'],
                'status' => 'lead',
                'assigned_to' => $assignedUserId,
                'custom_fields' => $customFields,
                'created_by' => $adminId,
                'created_at' => now()->subMinutes(($idx + 1) * 35),
                'updated_at' => now()->subMinutes(($idx + 1) * 35),
            ]);

            if (isset($comp['activity'])) {
                $act = $comp['activity'];
                ContactActivity::create([
                    'contact_id' => $contact->id,
                    'user_id' => $assignedUserId,
                    'type' => $act['type'],
                    'title' => $act['title'],
                    'description' => $act['description'],
                    'created_at' => now()->subMinutes(($idx + 1) * 15),
                    'updated_at' => now()->subMinutes(($idx + 1) * 15),
                ]);
            }
        }
    }
}
