import AppLayout from '@/Layouts/AppLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card'; import { Badge } from '@/Components/ui/badge'; import { Button } from '@/Components/ui/button'; import { Input } from '@/Components/ui/input'; import { useForm } from '@inertiajs/react'; import { Gift, Trophy } from 'lucide-react';
export default function RewardsIndex({ rewards, leaderboard, users }) {
    const { data, setData, post, processing } = useForm({ user_id: '', title: '', description: '', points: 10 }); const submit = (e) => { e.preventDefault(); post('/employees/rewards'); };
    return (<AppLayout title="Rewards" breadcrumbs={[{ label: 'Employees', href: '/employees' }, { label: 'Rewards' }]}>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            <div className="lg:col-span-2 space-y-6">
                <Card><CardHeader><CardTitle className="text-base">Award Reward</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><label className="text-sm font-medium">Employee</label><select className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={data.user_id} onChange={e => setData('user_id', e.target.value)} required><option value="">Select...</option>{(users || []).map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="space-y-2"><label className="text-sm font-medium">Points</label><Input type="number" min="1" value={data.points} onChange={e => setData('points', e.target.value)} /></div><div className="space-y-2"><label className="text-sm font-medium">Title</label><Input value={data.title} onChange={e => setData('title', e.target.value)} required /></div></div><Button type="submit" variant="gradient" size="sm" disabled={processing}>Award</Button></form></CardContent></Card>
                <Card><CardContent className="p-0"><table className="w-full"><thead><tr className="border-b border-border"><th className="text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground p-4">Employee</th><th className="text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground p-4">Reward</th><th className="text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground p-4">Points</th><th className="text-left text-[11px] font-bold uppercase tracking-wider text-muted-foreground p-4">Awarded By</th></tr></thead><tbody>{(rewards?.data || []).map(r => <tr key={r.id} className="border-b border-border/50"><td className="p-4 text-sm font-medium">{r.user?.name}</td><td className="p-4 text-sm">{r.title}</td><td className="p-4"><Badge variant="success">+{r.points}</Badge></td><td className="p-4 text-sm text-muted-foreground">{r.awarder?.name}</td></tr>)}</tbody></table></CardContent></Card>
            </div>
            <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Trophy className="h-5 w-5 text-amber-400" />Leaderboard</CardTitle></CardHeader><CardContent className="space-y-3">{(leaderboard || []).map((u, i) => <div key={u.id} className="flex items-center gap-3"><span className="text-lg font-bold w-6">{i + 1}</span><span className="text-sm flex-1">{u.name}</span><Badge variant="default">{u.rewards_sum_points || 0} pts</Badge></div>)}</CardContent></Card>
        </div></AppLayout>);
}
